# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dab5bfd7f91ed06c611d3cb10a75e78b1cb63980f166c30ac8cc9c48b02861b673d68b4f0f8a27da36a1a05e30e33dd615d7e3ef4c42178a4d1122723271ccf2

test:
  secret_key_base: 762ccebf85fed77ec39b1a82af60b1550ee19f31ae6d415f2cd714726aec586fc49c053ccc29d4f6fc4bd0f1e187074b20faec8a1d7b5ac6b7c31a81ba0cacc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
